config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'
  resources :photos
  devise_for :users

  get '/qrcode/:id', to: 'qrcode#download', as: 'qrcode'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActionController::RoutingError, :with => :render_404
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    def render_404
      render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show]

  def download
    qr = RQRCode::QRCode.new(url_for(@photo))
    png = qr.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 480
      )
      send_data png, type: Mime::Type.lookup("image/png"), disposition: 'inline'
  end
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.where(:user_id => current_user.id)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    qr = RQRCode::QRCode.new(url_for(@photo))
    @qrsvg = qr.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
#    @qrhtml = qr.as_html
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :caption, :image, :user_id)
    end
end

app/controllers/qrcode_controller.rb
class QrcodeController < ApplicationController
  before_action :set_photo, only: [:download]
    def download
      qr = RQRCode::QRCode.new(url_for(@photo))
      png = qr.as_png(
          bit_depth: 1,
          border_modules: 4,
          color_mode: ChunkyPNG::COLOR_GRAYSCALE,
          color: 'black',
          file: nil,
          fill: 'white',
          module_px_size: 6,
          resize_exactly_to: false,
          resize_gte_to: false,
          size: 480
        )
        send_data png, type: Mime::Type.lookup("image/png"), disposition: 'inline'
    end
    
    def set_photo
      @photo = Photo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagerepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="field">
  <div class="control">
    <%= f.input :title, input_html: {class:"input"}, label_html: {class:"label"}, wrapper: false%>
  </div>
  <div class="control">
    <%= f.input :caption, input_html: {class:"input"}, label_html: {class:"label"}, wrapper: false %>
  </div>
  <div class="control">
      <!--<%= f.file_field :image, input_html: {class:"button is-primary is-rounded"}, label_html: {class:"button is-primary is-rounded"}, wrapper: false %> -->
      <%= f.file_field :image, class: "file-label file-name", wrapper: false %>
  </div>
</div>

<div class="form-actions">
  <%= f.button :submit, class: "button is-primary is-rounded"%>
</div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<p id="notice"><%= notice %></p>
<br>
<div class="task-container columns is-multiline">
    <div class="card column is-half is-offset-one-quarter">
        <div class="card-content">
            <h1 class="title is-1">Edit Photo</h1>
            <%= render 'form', photo: @photo %>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                <span>
                    <%= link_to("Back", photos_path, class: "button is-info is-rounded") %>
                </span>
            </p>
        </footer>
    </div>
</div>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="task-container columns is-multiline">
  <div class="card column is-half is-offset-one-quarter">
    <div class="card-content">
      <h1 class="title is-1">Your Photos</h1>

      <div class="columns is-multiline">
        <% @photos.each do |photo| %>
        <div class="column is-half">
          <div class="box" style="max-width: 350px;">
            <a href=<%= photo_path(photo) %> 
              <figure class="image is-4by3" style="max-width:350;">
              <%= image_tag(photo.image) %>
              </figure>
              <div class="media">
                <div class="media-content" style="margin: 3px;">
                </div>
              </div>
            </a>
            <h6 class="title is-6" style="margin-top: 15px;"><%= photo.title %></h6>
<!--          <%= link_to "Delete", photo, method: :delete, class: "button is-info is-warning" %> -->
          <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger"%>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        <span>
          <a href=<%= new_photo_path %> class="button is-primary is-rounded">Upload</a>
        </span>
      </p>
      <p class="card-footer-item">
        <span>
          <%= link_to("Sign Out", destroy_user_session_path, method: :delete, class: "button is-info is-rounded") %>
        </span>
      </p>
    </footer>
  </div>
</div>

app/views/photos/new.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class="task-container columns is-multiline">
    <div class="card column is-half is-offset-one-quarter">
        <div class="card-content">
            <h1 class="title is-1">New Photo</h1>
            <%= render 'form', photo: @photo %>
        </div>
        <footer class="card-footer">
            <p class="card-footer-item">
                <span>
                    <%= link_to("Back", photos_path, class: "button is-info is-rounded") %>
                </span>
            </p>
        </footer>
    </div>
</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>



<br>
<div class="task-container columns is-multiline">
  <div class="card column is-half is-offset-one-quarter">
    <div class="card-content">
      <h1 class="title is-1"><%= @photo.title %></h1>
      <center>
      <div class="image is-1by" style="max-width: 400px; max-height: 200;">
        <%= image_tag(@photo.image) %>
      </div>
      <br>
      <h3 class="title is-3">Share with this QR code!</h3>
        <%= @qrsvg.html_safe %>
        <%= button_to "Download QR Code!", qrcode_path(:id => @photo.id), method: "get", class: "button is-primary" %>
      </center>
      <p>
        <strong>Caption:</strong>
        <%= @photo.caption %>
      </p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        <span>
          <%= link_to("Back", photos_path, class: "button is-info is-rounded") %>
        </span>
      </p>
      <p class="card-footer-item">
        <span>
          <%= link_to("Edit", edit_photo_path(@photo), class: "button is-danger is-rounded") %>
        </span>
      </p>
    </footer>
  </div>
</div>